import Head from 'next/head'
import { useState } from 'react'
import Field from '../components/Field'
import List from '../components/List'
import styles from '../styles/Home.module.css'
export default function Home() {
  const [Items, setItems] = useState([])
  const addItem = item => {
    const newItems = [ ...Items, item]
    setItems(newItems)
  }
  const deleteItem = id => {
    let newArr = [...Items].filter(item => item.id !== id)
    setItems(newArr)
  }
  // console.log(...Items)
  return (
    <div >
      <Head>
        <title>for of
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Field onSubmit={addItem}/>
        <List items={Items} deleteItem={deleteItem} setItems={setItems}/>
      </main>
      
    </div>
  )
}
